---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170715141010"
generator:
  name: "SpringBootSeed"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.7"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "b6b9f14be8b950ed2b962742091b2b4e035d848e"
    sha: "b6b9f14"
  parameters:
    - "description": "my new project"
    - "serviceClassName": "RestService"
    - "groupId": "com.kogonic"
    - "follows": "true"
    - "org": "atomist-seeds"
    - "artifactId": "bookings"
    - "repo": "spring-rest-seed"
    - "rootPackage": "bookings"
    - "version": "0.1.0-SNAPSHOT"
    - "branch": "master"
    - "visibility": "public"

